import { EditorState, EditorItem, TableData } from '../types/editor'

export const getMockEditorState = (): EditorState => {
  const titleItems: EditorItem[] = [
    {
      value: 'XX公司销售订单',
      x: 0,
      y: 10,
      width: 210,
      height: 15,
      fontSize: 22,
      bold: true,
      fontFamily: 'SimHei',
      fontColor: '#000000',
      verticalAlignment: 'center',
      horizontalAlignment: 'center',
      visible: true,
      type: 'text',
      name: 'Title',
      alias: '标题',
      field: 'title',
    },
  ]

  const headerItems: EditorItem[] = [
    {
      alias: '客户名称',
      field: 'customerName',
      name: '客户名称',
      type: 'text',
      x: 10,
      y: 30,
      width: 60,
      height: 7,
      value: '客户名称: 方13888350561',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '收货地址',
      field: 'address',
      name: '收货地址',
      type: 'text',
      x: 10,
      y: 40,
      width: 60,
      height: 7,
      value: '收货地址:',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '发货仓库',
      field: 'warehouseName',
      name: '发货仓库',
      type: 'text',
      x: 10,
      y: 50,
      width: 60,
      height: 7,
      value: '发货仓库: 昆明仓库',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '结算单位',
      field: 'settlementUnit',
      name: '结算单位',
      type: 'text',
      x: 10,
      y: 60,
      width: 60,
      height: 7,
      value: '结算单位: 方13888350561',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '结算方式',
      field: 'settleMethod',
      name: '结算方式',
      type: 'text',
      x: 80,
      y: 30,
      width: 60,
      height: 7,
      value: '结算方式: 现结',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '单据备注',
      field: 'remark',
      name: '单据备注',
      type: 'text',
      x: 80,
      y: 40,
      width: 60,
      height: 7,
      value: '单据备注:',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '收货电话',
      field: 'phone',
      name: '收货电话',
      type: 'text',
      x: 80,
      y: 50,
      width: 60,
      height: 7,
      value: '收货电话:',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '单号',
      field: 'billNo',
      name: '单号',
      type: 'text',
      x: 100,
      y: 60,
      width: 80,
      height: 7,
      value: '单号: XD-FMY-202512-0006',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '收货人',
      field: 'receiver',
      name: '收货人',
      type: 'text',
      x: 150,
      y: 35,
      width: 50,
      height: 7,
      value: '收货人:',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '客户分类',
      field: 'customerType',
      name: '客户分类',
      type: 'text',
      x: 150,
      y: 45,
      width: 50,
      height: 7,
      value: '客户分类:',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '客户编号',
      field: 'customerNo',
      name: '客户编号',
      type: 'text',
      x: 150,
      y: 55,
      width: 50,
      height: 7,
      value: '客户编号: .0323',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '录单时间',
      field: 'recordTime',
      name: '录单时间',
      type: 'text',
      x: 130,
      y: 68,
      width: 70,
      height: 7,
      value: '录单时间: 2025-12-08 16:38',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
  ]

  const footerItems: EditorItem[] = [
    {
      alias: '收款账户',
      field: 'accountName',
      name: '收款账户',
      type: 'text',
      x: 10,
      y: 240,
      width: 60,
      height: 7,
      value: '收款账户:',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '结算金额',
      field: 'settleAmount',
      name: '结算金额',
      type: 'text',
      x: 10,
      y: 250,
      width: 60,
      height: 7,
      value: '结算金额: 0.00',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '客户应收',
      field: 'customerDue',
      name: '客户应收',
      type: 'text',
      x: 10,
      y: 260,
      width: 60,
      height: 7,
      value: '客户应收: 0.00',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '本单应收',
      field: 'currentDue',
      name: '本单应收',
      type: 'text',
      x: 10,
      y: 270,
      width: 60,
      height: 7,
      value: '本单应收: 0.00',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '收款金额',
      field: 'receivedAmount',
      name: '收款金额',
      type: 'text',
      x: 80,
      y: 240,
      width: 60,
      height: 7,
      value: '收款金额: 0.00',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '预收余额',
      field: 'preReceivedBalance',
      name: '预收余额',
      type: 'text',
      x: 80,
      y: 250,
      width: 60,
      height: 7,
      value: '预收余额: 0.00',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '本单累计应收',
      field: 'totalDue',
      name: '本单累计应收',
      type: 'text',
      x: 80,
      y: 260,
      width: 60,
      height: 7,
      value: '本单累计应收: 0.00',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
    {
      alias: '此前应收',
      field: 'previousDue',
      name: '此前应收',
      type: 'text',
      x: 80,
      y: 270,
      width: 60,
      height: 7,
      value: '此前应收: 0.00',
      visible: true,
      fontSize: 11,
      fontFamily: 'SimHei',
      fontColor: '#000000',
    },
  ]

  const bodyItems: TableData = {
    cols: [
      {
        alias: '行号',
        colname: 'serialNumber',
        title: '行号',
        visible: true,
        width: 10,
      },
      {
        alias: '条码',
        colname: 'barCode',
        title: '条码',
        visible: true,
        width: 30,
      },
      {
        alias: '库存数量',
        colname: 'bookStockQty',
        title: '库存数量',
        visible: true,
        width: 20,
      },
      {
        alias: '单位',
        colname: 'unitName',
        title: '单位',
        visible: true,
        width: 10,
      },
      {
        alias: '数量',
        colname: 'qty',
        title: '数量',
        visible: true,
        width: 10,
      },
      {
        alias: '单价',
        colname: 'price',
        title: '单价',
        visible: true,
        width: 15,
      },
      {
        alias: '金额',
        colname: 'amount',
        title: '金额',
        visible: true,
        width: 20,
      },
      {
        alias: '可用库存量',
        colname: 'canUseQty',
        title: '可用库存量',
        visible: true,
        width: 40,
      },
      {
        alias: '自定义列1',
        colname: 'custom1',
        title: '自定义列1',
        visible: true,
        width: 8,
      },
      {
        alias: '自定义列2',
        colname: 'custom2',
        title: '自定义列2',
        visible: true,
        width: 8,
      },
      {
        alias: '自定义列3',
        colname: 'custom3',
        title: '自定义列3',
        visible: true,
        width: 8,
      },
      {
        alias: '自定义列4',
        colname: 'custom4',
        title: '自定义列4',
        visible: true,
        width: 8,
      },
      {
        alias: '自定义列5',
        colname: 'custom5',
        title: '自定义列5',
        visible: true,
        width: 20,
      },
    ],
  }

  // Use values from template.json directly
  return {
    headerTop: 30,
    bodyTop: 70,
    footerTop: 240,
    paperHeight: 297,
    paperWidth: 210,
    titleItems,
    headerItems,
    bodyItems,
    footerItems,
  }
}
