#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm if available
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use the node version from .nvmrc if it exists
if [ -f ".nvmrc" ]; then
  nvm use
fi

pnpm exec lint-staged
